insert into Usuario (username, password, nome, perfil) values ('demo', 'demo', 'Usuario Demo', null)
insert into Projeto (id, nome, cliente, localizacao, descricaoBreve, descricao) values (1, 'Projeto X', '1', 'Jardim Botanico, Rio de Janeiro', 'xxxxx', 'Em construcao')
insert into Projeto (id, nome, cliente, localizacao, descricaoBreve, descricao) values (2, 'Projeto Y', '1', 'Marte , Espaco', 'yyyyyy', 'Em construcao')
insert into Projeto (id, nome, cliente, localizacao, descricaoBreve, descricao) values (3, 'Projeto Z', '1', 'Jupiter', 'zzzzzz', 'Em construcao')
insert into Projeto (id, nome, cliente, localizacao, descricaoBreve, descricao) values (4, 'Projeto A', '1', 'Saturno', 'aaaaaa', 'Em construcao')
insert into Projeto (id, nome, cliente, localizacao, descricaoBreve, descricao) values (5, 'Projeto B', '1', 'Urano', 'bbbbbb', 'Em construcao')
insert into Projeto (id, nome, cliente, localizacao, descricaoBreve, descricao) values (6, 'Projeto C', '1', 'Netuno', 'cccccc', 'Em construcao')
insert into Tarefa (id, projeto_id, usuario_username, nome, prazo,  urgencia, descricaoBreve, descricao, andamento, arquivos) values (1, 1, 'demo','YYYYYY', 'julho, 2010', 'Para Ontem', 'descricao breve', 'descricao longa', 'Allegro',  '2000')
insert into Tarefa (id, projeto_id, usuario_username, nome, prazo,  urgencia, descricaoBreve, descricao, andamento, arquivos) values (2, 1, 'demo',  'ZZZZZZ', 'julho 2010', 'Para Ontem', 'descricao breve', 'descricao longa','Moderato', 'NW13UP')
insert into Tarefa (id, projeto_id, usuario_username, nome, prazo,  urgencia, descricaoBreve, descricao, andamento, arquivos) values (3, 1, null, 'XXXXX', 'agosto, 2010', 'Para Ontem', 'descricao breve', 'descricao longa','Andante', '60601')
insert into Tarefa (id, projeto_id, usuario_username, nome, prazo,  urgencia, descricaoBreve, descricao, andamento, arquivos) values (4, 2, 'demo', 'AAAAA', 'junho 2010', 'Para Ontem', 'descricao breve', 'descricao longa','Lento', '30326')
